version: '3'

services:
  router:
    image: traefik:2.3
    volumes:
      - ./etc/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./etc/traefik/services:/etc/traefik/services
      - ./etc/traefik/certificates:/etc/traefik/certificates
    ports:
      - 80:80
      - 443:443
      - 8080:8080
