[http]
  [http.routers]
    [http.routers.elastichq]
      entryPoints = ["websecure"]
      service = "elastichq"
      rule = "Host(`elastichq.demo.local`)"
      [http.routers.elastichq.tls]

  [http.services]
    [http.services.elastichq]
      [http.services.elastichq.loadBalancer]
        [[http.services.elastichq.loadBalancer.servers]]
          url = "http://elastichq:5000"
