[global]
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.file]
    directory = "/etc/traefik/services"

[api]
  insecure = true
  dashboard = true
